web:
  build: .
  command: "python -u app.py"
  volumes:
    - .:/app
  ports:
    - "5000:5000"
  links:
    - db
db:
  image: mongo:latest
  volumes:
    - ./data:/data/db
  ports:
    - "27017:27017"